name: Build Caddy

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up XCaddy
      run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: Build
      run: ~/go/bin/xcaddy build --with github.com/izumi46/caddy-replace-token=. --with github.com/mholt/caddy-l4 --with github.com/caddy-dns/cloudflare --with github.com/WeidiDeng/caddy-cloudflare-ip --with github.com/caddyserver/replace-response --with github.com/abiosoft/caddy-yaml --with github.com/abiosoft/caddy-json-parse

    - name: Get Caddy Version
      id: get_version
      run: |
        echo version=$(./caddy version| awk '{print $1}') >> "$GITHUB_OUTPUT"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        files: caddy
